dataset:
  category: grid
  center_crop: null
  eval_batch_size: 16
  format: mvtec
  image_size: 256
  inference_batch_size: 16
  name: mvtec
  normalization: imagenet
  num_workers: 8
  path: ./datasets/MVTec
  task: segmentation
  test_split_mode: from_dir
  test_split_ratio: 0.2
  train_batch_size: 16
  transform_config:
    eval: null
    train: null
  val_split_mode: same_as_test
  val_split_ratio: 0.5
logging:
  log_graph: false
  logger: []
metrics:
  image:
  - F1Score
  - AUROC
  pixel:
  - F1Score
  - AUROC
  threshold:
    manual_image: null
    manual_pixel: null
    method: adaptive
model:
  backbone: wide_resnet50_2
  clamp_alpha: 1.9
  condition_vector: 128
  coupling_blocks: 8
  decoder: freia-cflow
  early_stopping:
    metric: pixel_AUROC
    mode: max
    patience: 2
  fiber_batch_size: 64
  layers:
  - layer2
  - layer3
  - layer4
  lr: 0.0001
  name: cflow
  normalization_method: min_max
  permute_soft: false
  pre_trained: true
optimization:
  export_mode: null
project:
  path: ./results
  seed: 0
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  auto_lr_find: false
  auto_scale_batch_size: false
  benchmark: false
  check_val_every_n_epoch: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gradient_clip_algorithm: norm
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 50
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  track_grad_norm: -1
  val_check_interval: 1.0
visualization:
  image_save_path: null
  log_images: true
  mode: full
  save_images: true
  show_images: false
